yiisoft/db-oracle

- README.md
- composer.json
- docs/guide/README.md
- docs/guide/installation.md
`yii(2)-oracle` => `db-oracle`
> Fix package name

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
- .scrutinizer.yml
- README.md
- composer.json
- infection.json.dist
- phpunit.xml.dist
- psalm.xml
> Add GitHub actions

- .scrutinizer.yml
> Fix external code coverage.

- composer.json
- src/Connection.php
- src/Schema.php
- tests/CommandTest.php
- tests/ConnectionTest.php
- tests/TestCase.php
| Fixed issues  | https://github.com/yiisoft/db/pull/197
> Split cache from Connection::class.

- src/Schema.php
- tests/ConnectionTest.php
- tests/TestCase.php
| Fixed issues  | https://github.com/yiisoft/db/pull/206
> Fix changes cache.

- README.md
- tests/ConnectionTest.php
- tests/TestCase.php
> Clean up update last change cache.

- composer.json
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
- src/TableSchema.php
- tests/ConnectionTest.php
- tests/TestCase.php
| Issue | https://github.com/yiisoft/db/pull/215
> Rework code.

- tests/TestCase.php
> Fixed tests.

- src/PDO/CommandPDOOracle.php
- src/PDO/SchemaPDOOracle.php
> Fix method `convertException()` (#277).

- src/PDO/CommandPDOOracle.php
- src/PDO/QueryBuilderPDOOracle.php
| Fixed issues  | https://github.com/yiisoft/db/pull/283
> Set error level psalm to 2.

- src/PDO/CommandPDOOracle.php
> Third step of remove PDO. Using only fetchAll

- src/PDO/CommandPDOOracle.php
> Step 4. Remove PDO (work with internalQuery)

- src/PDO/CommandPDOOracle.php
> Fix static analisys.

- src/PDO/CommandPDOOracle.php
> Fix psalm-1.

- src/PDO/CommandPDOOracle.php
- src/PDO/ConnectionPDOOracle.php
- src/PDO/QueryBuilderPDOOracle.php
- src/PDO/SchemaPDOOracle.php
- tests/ConnectionTest.php
- tests/SchemaTest.php
> Simplification of Connection - removing pool from Connection

- src/PDO/SchemaPDOOracle.php
> Psalm fixes

- src/DMLQueryBuilder.php
- src/PDO/ConnectionPDOOracle.php
- src/PDO/QueryBuilderPDOOracle.php
> Common constructor for ConnectionPDO

- src/PDO/CommandPDOOracle.php
- src/PDO/ConnectionPDOOracle.php
- src/PDO/SchemaPDOOracle.php
- tests/ConnectionTest.php
> Removing getDriver from ConnectionPDO classes

- src/PDO/ConnectionPDOOracle.php
- src/PDO/SchemaPDOOracle.php
- tests/CommandTest.php
> Refactoring lastInsertId

- src/PDO/ConnectionPDOOracle.php
- src/Schema.php
- tests/CommandTest.php
> Remove PDO from Schemas

- src/PDO/CommandPDOOracle.php
- src/Schema.php
- tests/SchemaTest.php
> Changed strings to constants. Added tests.

- src/ColumnSchema.php
- src/PDO/CommandPDOOracle.php
- src/PDO/ConnectionPDOOracle.php
- src/PDO/TransactionPDOOracle.php
- tests/CommandTest.php
- tests/TestCase.php
> Move classes `PDO` to directory `src/Driver/PDO`.

- src/Schema.php
> Fix tests psalm.

- psalm.xml
- src/PDO/ConnectionPDOOracle.php
- src/PDO/QueryBuilderPDOOracle.php
- src/Schema.php
- src/TableSchema.php
- tests/CommandTest.php
- tests/QueryBuilderTest.php
- tests/SchemaTest.php
> Fixes after using psalm with folder `tests`

- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- src/DQLQueryBuilder.php
- src/PDO/CommandPDOOracle.php
- src/PDO/QueryBuilderPDOOracle.php
> Use injection dependencies, remove dependencie transitive.

- src/PDO/QueryBuilderPDOOracle.php
- tests/SchemaTest.php
> Refactoring createIndex and more cleanup of code

- src/PDO/ConnectionPDOOracle.php
- src/PDO/PDODriver.php
- tests/ConnectionTest.php
- tests/TestCase.php
> Work with attributes on connection

- src/PDO/ConnectionPDOOracle.php
> Unused check of exists constant

- src/CommandPDO.php
- src/ConnectionPDO.php
- src/PDODriver.php
- src/QueryBuilder.php
- src/TransactionPDO.php
- tests/QueryBuilderTest.php
- tests/TestCase.php
> Remove `PDO` folders in subpackages

- src/ColumnSchema.php
- tests/CommandTest.php
> Removed "as array" and PdoValue behaviour from bindValues function.

- src/ConnectionPDO.php
> Fix tests quoter.

- src/DMLQueryBuilder.php
- tests/Provider/QueryBuilderProvider.php
> Bugfix for normalize names of columns

- tests/CommandTest.php
> Improve test coverage

- src/Schema.php
> Fixes from yii2 #18435, #18442

- tests/ConnectionTest.php
> Fix for serialized test

- .github/actions/subpackage_install/action.yml
- .github/workflows/build.yml
- src/DQLQueryBuilder.php
> Expression -> ExpressionInterface refactoring

- src/QueryBuilder.php
- tests/QueryBuilderTest.php
- tests/SchemaTest.php
| Fixed issues  | https://github.com/yiisoft/db-mysql/issues/133
> Const optimization

- tests/CommandTest.php
> Add test for Profiler

- tests/Provider/SchemaProvider.php
- tests/Support/Fixture/oci.sql
| Fixed issues  | https://github.com/yiisoft/db/issues/264
> Fix for typecast decimal columns

- tests/CommandTest.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Profiler context

- src/Column.php
- src/DDLQueryBuilder.php
- src/Schema.php
> Rename class ColumnSchemaBuilder

- .github/workflows/build.yml
- .github/workflows/composer-require-checker.yml
- .github/workflows/mutation.yml
- .github/workflows/rector.yml
- .github/workflows/static.yml
- .scrutinizer.yml
> Fix scrutinizer test, add concurrency github actions.

- src/Dsn.php
| Fixed issues  | resolve https://github.com/yiisoft/db-oracle/issues/264
> update src folder link

- CHANGELOG.md
- src/Command.php
- src/Schema.php
- tests/Provider/SchemaProvider.php
- yiisoft/db#862
| Fixed issues  | yiisoft/db#861
> Refactor column PHP type

- CHANGELOG.md
- src/Dsn.php
- tests/Support/TestTrait.php
> Refactor `Dsn` class

- CHANGELOG.md
- src/Column/ColumnFactory.php
- src/Schema.php
- tests/ColumnFactoryTest.php
- tests/Provider/ColumnFactoryProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/898
> Refactor normalizeDefaultValue()

- CHANGELOG.md
- src/Connection.php
- src/QueryBuilder.php
- tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/906
> Update according to changes in `db`

- CHANGELOG.md
- src/Column/BinaryColumn.php
- src/Column/ColumnBuilder.php
- src/Column/ColumnDefinitionBuilder.php
- src/Column/ColumnFactory.php
- src/Command.php
- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- src/Schema.php
- tests/ColumnTest.php
- tests/Provider/ColumnBuilderProvider.php
- tests/Provider/ColumnFactoryProvider.php
- tests/Provider/ColumnProvider.php
- tests/QueryBuilderTest.php
- tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/917
> Rename `ColumnSchemaInterface` to `ColumnInterface`

- CHANGELOG.md
- src/Connection.php
- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
> Explicitly mark nullable parameters

- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/982
> Update tests according to changes in `db`

- CHANGELOG.md
- src/DMLQueryBuilder.php
- src/Schema.php
- tests/CommandTest.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/981
> Refactor constraints

- tests/Provider/QueryBuilderProvider.php
Related to https://github.com/yiisoft/db/pull/1000
> Prepare values in hash condition

- src/Builder/InBuilder.php
- src/DQLQueryBuilder.php
Related to https://github.com/yiisoft/db/pull/1019
> Adapt to split `In` condition in Yii DB

- CHANGELOG.md
- src/Column/ColumnDefinitionBuilder.php
- src/Schema.php
- tests/Provider/QueryBuilderProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/1020
> Support column's collation

- CHANGELOG.md
- src/Connection.php
- tests/ColumnBuilderTest.php
- tests/ColumnTest.php
- tests/ConnectionTest.php
- https://github.com/yiisoft/db/pull/1034
> Add `Connection::getColumnBuilderClass()`

- src/Builder/LikeBuilder.php
Related to https://github.com/yiisoft/db/pull/1062
> Adapt to `Stringable` value support in `Like`
