- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/ConnectionTest.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
- tests/TestCase.php
> Refactoring of batchInsert (for remove using of Quoter)

- tests/ColumnSchemaTest.php
- tests/Provider/SchemaProvider.php
- tests/Support/Fixture/oci.sql
> Add ColumnSchemaTest

- src/Command.php
> Fix psalm issue (#233)

- src/Command.php
> Fix psalm issue (#233) better solution

- CHANGELOG.md
- src/DQLQueryBuilder.php
`RECURSIVE` expression is not needed In Oracle CTE
Related with yiisoft/db#761
> Fix CTE query expressions

- CHANGELOG.md
- src/Command.php
**Related with yiisoft/db#770**
> Move methods from `Command` to `AbstractPDOCmmand` class

- CHANGELOG.md
- src/DMLQueryBuilder.php
- tests/Provider/CommandProvider.php
Related with yiisoft/db#769
| Fixed issues  | yiisoft/db#61
> Fix `batchInsert()` with associative arrays

- CHANGELOG.md
- src/Command.php
* yiisoft/db#791
| Fixed issues  | yiisoft/db#792
> Fix `Command::insertWithReturningPks()`

- CHANGELOG.md
- rector.php
- src/Builder/ExpressionBuilder.php
- src/ColumnSchema.php
- src/DQLQueryBuilder.php
- src/SqlParser.php
- tests/CommandTest.php
- tests/Provider/SqlParserProvider.php
- tests/QueryBuilderTest.php
- tests/SqlParserTest.php
> Update test according to main PR

- CHANGELOG.md
- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/Provider/CommandProvider.php
- tests/QueryBuilderTest.php
> Update according to the main PR

- CHANGELOG.md
- src/Command.php
- src/Schema.php
| Fixed issues  | yiisoft/db#767
> Replace call of `SchemaInterface::getRawTableName()` to `QuoterInterface::getRawTableName()`

- CHANGELOG.md
- src/Column/ColumnBuilder.php
- src/Column/ColumnFactory.php
- src/Dsn.php
- src/Schema.php
- https://github.com/yiisoft/db/pull/890
> Load column properties via constructor

- CHANGELOG.md
- src/Column/ColumnFactory.php
- src/Schema.php
- tests/ColumnSchemaTest.php
- tests/Provider/SchemaProvider.php
- tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/897
> Refactor `ColumnFactory`

- CHANGELOG.md
- src/Builder/LikeConditionBuilder.php
- src/Command.php
- src/QueryBuilder.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/902
> Add `QueryBuilder::prepareBinary()` method

- CHANGELOG.md
- src/Column/BinaryColumn.php
- src/Column/ColumnDefinitionBuilder.php
- src/Column/ColumnDefinitionParser.php
- src/Column/ColumnFactory.php
- src/Command.php
- src/Schema.php
- tests/ColumnDefinitionParserTest.php
- tests/ColumnTest.php
- tests/Provider/ColumnDefinitionParserProvider.php
- tests/Provider/ColumnFactoryProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/922
> Fix `ColumnDefinitionParser`

- CHANGELOG.md
- src/IndexType.php
- src/Schema.php
- tests/CommandTest.php
- tests/Provider/CommandProvider.php
- https://github.com/yiisoft/db/pull/920
> Create `IndexType` class

- CHANGELOG.md
- src/Column/ColumnDefinitionBuilder.php
- src/Schema.php
- tests/Provider/QueryBuilderProvider.php
- https://github.com/yiisoft/db/pull/928
> Use constants from `ReferentialAction` class

- .github/workflows/bc.yml_
- .github/workflows/build.yml
- .github/workflows/composer-require-checker.yml
- .github/workflows/mutation.yml
- .github/workflows/rector.yml
- .github/workflows/static.yml
- CHANGELOG.md
- README.md
- composer.json
- psalm.xml
- src/Column/ColumnDefinitionParser.php
- src/Column/JsonColumn.php
- src/Command.php
- src/Schema.php
- tests/CommandTest.php
- tests/QuoterTest.php
- https://github.com/yiisoft/db/pull/911
> Test PHP 8.4

- CHANGELOG.md
- src/Builder/LikeConditionBuilder.php
- src/Column/ColumnDefinitionBuilder.php
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
- tests/ConnectionTest.php
- tests/SchemaTest.php
according to changes in main `db` package
- https://github.com/yiisoft/db/pull/940
> Refactoring

- CHANGELOG.md
- src/Column/BooleanColumn.php
- src/Column/ColumnBuilder.php
- src/Column/ColumnDefinitionBuilder.php
- src/Column/ColumnFactory.php
- src/QueryBuilder.php
- tests/ColumnTest.php
- tests/Provider/ColumnBuilderProvider.php
- tests/Provider/ColumnFactoryProvider.php
- tests/Provider/ColumnProvider.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/active-record/pull/408
> Support `boolean` type

- src/Connection.php
- tests/CommandTest.php
- tests/PdoConnectionTest.php
Related to https://github.com/yiisoft/db/pull/965
> Rename `getLastInsertID()` method in `ConnectionInterface` to `getLastInsertId()`

- CHANGELOG.md
- src/Command.php
- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/QueryBuilderTest.php
- tests/Support/Fixture/oci.sql
- https://github.com/yiisoft/db/pull/973
> Refactor `Command::insertWithReturningPks()` method

- CHANGELOG.md
- src/Command.php
- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/Provider/CommandPDOProvider.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
- tests/Support/Fixture/oci.sql
- tests/Support/TestTrait.php
- https://github.com/yiisoft/db/pull/976
> Refactor `DMLQueryBuilder::upsert()`

- CHANGELOG.md
- src/Command.php
- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/985
> Rename `insertWithReturningPks()` to `insertReturningPks()`

- CHANGELOG.md
- src/Builder/InConditionBuilder.php
- src/Connection.php
- src/DMLQueryBuilder.php
- tests/PdoConnectionTest.php
- tests/QueryBuilderTest.php
| Fixed issues  | [729 - yiisoft/db](https://github.com/yiisoft/db/issues/729)
> Replace Db\InvalidArgumentException to \InvalidArgumentException

- CHANGELOG.md
- src/Builder/InConditionBuilder.php
- src/Builder/LikeConditionBuilder.php
Related to https://github.com/yiisoft/db/pull/1002
> Adapt to specific condition interfaces removing in `yiisoft/db` package

- CHANGELOG.md
- src/Builder/InBuilder.php
- src/Builder/LikeBuilder.php
- src/DQLQueryBuilder.php
Related to https://github.com/yiisoft/db/pull/1006
> Remove "Condition" suffix from condition classes

- tests/Provider/QueryBuilderProvider.php
Related to https://github.com/yiisoft/db/pull/1007
> Adapt tests to changes in Yii DB

- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
| Fixed issues  | 
- https://github.com/yiisoft/db/pull/1054
> Adapt for changes in `db`

- CHANGELOG.md
- src/DMLQueryBuilder.php
- tests/CommandTest.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
| Fixed issues  | yiisoft/db#94
> Adapt to db changes
